import mongoose from "mongoose";
import bcyrpt from "bcryptjs";
import JWT from "jsonwebtoken";
import crypto from "crypto";

import AuthRoles from "../utils/authRoles.js";
import config from "../config/index.js";

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: ["true", "Name must be provided"],
    maxLength: [50, "Name must be less than 50 characters"],
    trim: true,
  },

  email: {
    type: String,
    required: ["true", "Email must be provided"],
  },
  password: {
    type: String,
    required: ["true", "Password must be provided"],
    minLength: [8, "Password must be at least 8 chars"],
    select: false,
  },
  role: {
    type: String,
    enum: Object.values(AuthRoles),
    default: AuthRoles.USER,
  },
  forgotPasswordToken: String,
  forgotPasswordExpiry: Date,
});

// hooks
userSchema.pre("save", async function (next) {
  if (!this.isModified("password")) return next();
  this.password = await bcyrpt.hash(this.password, 12);
  next();
});

// methods
userSchema.methods = {
  // compare password
  comparePassword: async function (enteredPassword) {
    return await bcyrpt.compare(enteredPassword, this.password);
  },
  //   generate jwttoken
  getJWTtoken: function () {
    JWT.sign({}, config.JWT_SECRET, {
      expiresIn: config.JWT_EXPIRY,
    });
  },
  // generate forgot password token
  generateForgotPasswordToken: function () {
    const forgotToken = crypto.randomBytes(20).toString("hex");

    // encrypt the token generated by crypto
    this.forgotPasswordToken = crypto
      .createHash("sha256")
      .update(forgotToken)
      .digest("hex");

    // time for token to expire
    this.forgotPasswordExpiry = Date.now() + 20 * 60 * 1000;
    return forgotToken;
  },
};
export default mongoose.model();
